export const spheres = [
  { name: "Ruby", color: "red" },
  { name: "Sapphire", color: "blue" },
  { name: "Emerald", color: "green" },
  { name: "Diamond", color: "white" },
  { name: "Amethyst", color: "purple" },
  { name: "Topaz", color: "yellow" },
  { name: "Opal", color: "multicolor" },
  { name: "Garnet", color: "dark-red" },
  { name: "Peridot", color: "light-green" },
  { name: "Aquamarine", color: "light-blue" },
  { name: "Citrine", color: "yellow" },
  { name: "Tanzanite", color: "blue-purple" },
  { name: "Morganite", color: "pink" },
  { name: "Alexandrite", color: "color-changing" },
  { name: "Tourmaline", color: "multi" },
  { name: "Kunzite", color: "pink-purple" },
  { name: "Labradorite", color: "iridescent" },
  { name: "Moonstone", color: "white-blue" },
  { name: "Sunstone", color: "orange" },
  { name: "Zircon", color: "blue" },
  { name: "Spinel", color: "red" },
  { name: "Chrysoberyl", color: "yellow-green" },
  { name: "Andalusite", color: "brown-green" },
  { name: "Apatite", color: "blue-green" },
  { name: "Azurite", color: "deep-blue" },
  { name: "Benitoite", color: "blue" },
  { name: "Beryl", color: "green" },
  { name: "Carnelian", color: "orange-red" },
  { name: "Chalcedony", color: "white-gray" },
  { name: "Chrysocolla", color: "blue-green" },
  { name: "Coral", color: "red-pink" },
  { name: "Danburite", color: "colorless" },
  { name: "Diaspore", color: "color-changing" },
  { name: "Dumortierite", color: "blue" },
  { name: "Fluorite", color: "multi" },
  { name: "Goshenite", color: "colorless" },
  { name: "Hauyne", color: "blue" },
  { name: "Heliodor", color: "yellow-green" },
  { name: "Hiddenite", color: "green" },
  { name: "Iolite", color: "blue-violet" },
  { name: "Jade", color: "green" },
  { name: "Jasper", color: "red" },
  { name: "Kyanite", color: "blue" },
  { name: "Larimar", color: "blue" },
  { name: "Lapis Lazuli", color: "deep-blue" },
  { name: "Malachite", color: "green" },
  { name: "Moldavite", color: "green" },
  { name: "Obsidian", color: "black" },
  { name: "Onyx", color: "black" },
  { name: "Pearl", color: "white" },
  { name: "Phenakite", color: "colorless" },
  { name: "Prehnite", color: "light-green" },
  { name: "Pyrite", color: "metallic-gold" },
  { name: "Quartz", color: "clear" },
  { name: "Rhodochrosite", color: "pink" },
  { name: "Rhodonite", color: "pink" },
  { name: "Rose Quartz", color: "pink" },
  { name: "Rutile", color: "reddish-brown" },
  { name: "Scapolite", color: "yellow" },
  { name: "Scheelite", color: "white" },
  { name: "Seraphinite", color: "green" },
  { name: "Serpentine", color: "green" },
  { name: "Smithsonite", color: "blue-green" },
  { name: "Sodalite", color: "blue" },
  { name: "Sphalerite", color: "brown" },
  { name: "Sphene", color: "green" },
  { name: "Spodumene", color: "pink" },
  { name: "Sugilite", color: "purple" },
  { name: "Taaffeite", color: "lavender" },
  { name: "Thulite", color: "pink" },
  { name: "Tiger's Eye", color: "golden-brown" },
  { name: "Topazolite", color: "yellow" },
  { name: "Tsavorite", color: "green" },
  { name: "Turquoise", color: "blue-green" },
  { name: "Variscite", color: "green" },
  { name: "Vesuvianite", color: "green" },
  { name: "Zoisite", color: "blue" },
  { name: "Amber", color: "yellow" },
  { name: "Ammolite", color: "iridescent" },
  { name: "Charoite", color: "purple" },
  { name: "Chrysoprase", color: "green" },
  { name: "Diopside", color: "green" },
  { name: "Eudialyte", color: "red" },
  { name: "Hemimorphite", color: "blue" },
  { name: "Howlite", color: "white" },
  { name: "Jet", color: "black" },
  { name: "Kornerupine", color: "green" },
  { name: "Lepidolite", color: "lilac" },
  { name: "Meteorite", color: "dark-gray" },
  { name: "Nuummite", color: "iridescent" },
  { name: "Pietersite", color: "blue-brown" },
  { name: "Poudretteite", color: "pink" },
  { name: "Spectrolite", color: "iridescent" },
]

export const sphereDetails = {
  Ruby: {
    description:
      "A deep red gemstone known for its passion and energy. Rubies are considered one of the four precious stones, along with sapphires, emeralds, and diamonds.",
    image:
      "https://images.unsplash.com/photo-1601058268499-e52658b8bb88?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cnVieXxlbnwwfHwwfHx8MA%3D%3D",
    properties: "Hardness: 9 on the Mohs scale, Birthstone: July, Chakra: Root",
    care: "Clean with warm soapy water and a soft brush. Avoid harsh chemicals and ultrasonic cleaners.",
  },
  Sapphire: {
    description:
      "A blue gemstone symbolizing wisdom and royalty. While most famous for its blue variety, sapphires can come in almost any color except red.",
    image:
      "https://images.unsplash.com/photo-1615486363973-f79d875780cf?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2FwcGhpcmV8ZW58MHx8MHx8fDA%3D",
    properties: "Hardness: 9 on the Mohs scale, Birthstone: September, Chakra: Throat",
    care: "Clean with mild dish soap and warm water. Use a soft toothbrush to remove dirt from crevices.",
  },
  // Add details for all 96 spheres here...
}

